version: 43.0.9
pageUuid: ddd83324-da84-11eb-a59e-17369d413594
appTemplate:
  tests:
    array: []
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  testEntities:
    array: []
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.72.1
  responsiveLayoutDisabled: false
  createdAt: null
  customShortcuts:
    array: []
  loadingIndicatorsDisabled: false
