version: 43.0.9
pageUuid: b12c211a-d3c1-11eb-ab8a-776161ee8282
appTemplate:
  testEntities:
    array:
      - object:
          id: dcdf0a3c-3ddb-4bbd-85e2-8d889a7f8660
          name: suite1 43423423
          hooks:
            array:
              - object:
                  type: 3
                  body: ''
              - object:
                  type: 2
                  body: ''
              - object:
                  type: 1
                  body: ''
              - object:
                  type: 0
                  body: ''
          type: suite
          tests:
            array:
              - object:
                  id: 034ac4b7-9236-4926-89fd-2def690818d2
                  name: test1
                  body: |-


                    assertCondition(textInput1.value=== 's')
                  type: test
                  pauseAllQueries: true
                  failureMessage: |
                    Failure at line 3: assertCondition failed.

                    The value you referenced was:
                    textInput1.value: "test"
                  suiteId: dcdf0a3c-3ddb-4bbd-85e2-8d889a7f8660
              - object:
                  id: aa618184-aff6-499a-a436-c377b35db295
                  name: test3
                  body: assertCondition(2 % 2 === )
                  type: test
                  pauseAllQueries: false
                  failureMessage: Unexpected token ')'
                  suiteId: dcdf0a3c-3ddb-4bbd-85e2-8d889a7f8660
              - object:
                  id: a7851d8e-ef77-401e-89fd-6b45b1ee3677
                  name: test4
                  body: ''
                  type: test
                  pauseAllQueries: false
                  failureMessage: null
                  suiteId: dcdf0a3c-3ddb-4bbd-85e2-8d889a7f8660
          pauseAllQueries: false
      - object:
          id: e6cd7dc4-8e23-4f26-890b-9a00dc6bbb8e
          name: suite1
          hooks:
            array:
              - object:
                  type: 3
                  body: ''
              - object:
                  type: 2
                  body: ''
              - object:
                  type: 1
                  body: ''
              - object:
                  type: 0
                  body: ''
          type: suite
          tests:
            array:
              - object:
                  id: c3af6622-fa5d-441b-8863-bd39144b091e
                  name: test2
                  body: ''
                  type: test
                  pauseAllQueries: false
                  suiteId: e6cd7dc4-8e23-4f26-890b-9a00dc6bbb8e
                  failureMessage: null
              - object:
                  id: 2973d556-451c-420f-8df4-e45e0657352b
                  name: test5
                  body: ''
                  type: test
                  pauseAllQueries: false
                  suiteId: e6cd7dc4-8e23-4f26-890b-9a00dc6bbb8e
                  failureMessage: null
          pauseAllQueries: false
      - object:
          id: 14a27e53-be8d-43f5-b2f4-96094e885fe3
          name: suite2
          hooks:
            array:
              - object:
                  type: 3
                  body: ''
              - object:
                  type: 2
                  body: ''
              - object:
                  type: 1
                  body: ''
              - object:
                  type: 0
                  body: ''
          type: suite
          tests:
            array: []
          pauseAllQueries: false
  version: 2.76.13
