version: 43.0.9
pageUuid: 2f1eff32-fc87-11eb-8b4f-bbccc7ee7ec4
appTemplate:
  testEntities:
    array:
      - object:
          id: c86f430f-5e5a-408d-a406-8e59fa125837
          name: test1
          body: console.log('hello!')
          state: 0
          type: test
          pauseAllQueries: false
          failureMessage: null
      - object:
          id: ebce161d-3b0f-4900-9da5-c8d7b02b99e1
          name: test2
          body: console.log('hello')
          state: 0
          type: test
          pauseAllQueries: false
          failureMessage: null
  version: 2.74.4
